/*
 * generated by Xtext
 */
package nl.dslmeinte.xtext.wsdl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class WsdlLanguageUiModule extends nl.dslmeinte.xtext.wsdl.ui.AbstractWsdlLanguageUiModule {
	public WsdlLanguageUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
