/*
 * generated by Xtext
 */
package nl.dslmeinte.xtext.express.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ExpressUiModule extends nl.dslmeinte.xtext.express.ui.AbstractExpressUiModule {
	public ExpressUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
