/*
 * generated by Xtext
 */
package nl.dslmeinte.xtext.ambiguity.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class MyPLUiModule extends nl.dslmeinte.xtext.ambiguity.ui.AbstractMyPLUiModule {
	public MyPLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
