/*
* generated by Xtext
*/
package nl.dslmeinte.xtext.express.base.ui.contentassist;

import nl.dslmeinte.xtext.express.base.ui.contentassist.AbstractBaseProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class BaseProposalProvider extends AbstractBaseProposalProvider {

}
