/*
 * generated by Xtext
 */
package nl.dslmeinte.xtext.express;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ExpressRuntimeModule extends nl.dslmeinte.xtext.express.AbstractExpressRuntimeModule {

}
