/*
 * generated by Xtext
 */
package nl.dslmeinte.xtext.wsdl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class WsdlLanguageRuntimeModule extends nl.dslmeinte.xtext.wsdl.AbstractWsdlLanguageRuntimeModule {

}
