/*
* generated by Xtext
*/
package nl.dslmeinte.xtext.express.expression.ui.contentassist;

import nl.dslmeinte.xtext.express.expression.ui.contentassist.AbstractExpressionProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class ExpressionProposalProvider extends AbstractExpressionProposalProvider {

}
