/*
 * generated by Xtext
 */
package nl.dslmeinte.xtext.express.expression.scoping;

import nl.dslmeinte.xtext.express.base.scoping.BaseScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation/latest/xtext.html#scoping
 * on how and when to use it 
 *
 */
public class ExpressionScopeProvider extends BaseScopeProvider {

}
