/*
 * generated by Xtext
 */
package nl.dslmeinte.xtext.express.base.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class BaseUiModule extends nl.dslmeinte.xtext.express.base.ui.AbstractBaseUiModule {
	public BaseUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
