/*
 * generated by Xtext
 */
package nl.dslmeinte.xtext.dtd.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class DtdUiModule extends nl.dslmeinte.xtext.dtd.ui.AbstractDtdUiModule {
	public DtdUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
