/*
 * generated by Xtext
 */
package nl.dslmeinte.xtext.examples.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class DataModelDslUiModule extends nl.dslmeinte.xtext.examples.ui.AbstractDataModelDslUiModule {
	public DataModelDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
