/*
 * generated by Xtext
 */
package nl.dslmeinte.xtext.xsd.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class XsdLanguageUiModule extends nl.dslmeinte.xtext.xsd.ui.AbstractXsdLanguageUiModule {
	public XsdLanguageUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
