/*
 * generated by Xtext
 */
package nl.dslmeinte.multilevel;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ExampleDslRuntimeModule extends nl.dslmeinte.multilevel.AbstractExampleDslRuntimeModule {

}
