/*
* generated by Xtext
*/
package nl.dslmeinte.xtext.examples.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class DataModelDslOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
