/*
* generated by Xtext
*/
package nl.dslmeinte.xtext.wsdl.ui.contentassist;

import nl.dslmeinte.xtext.wsdl.ui.contentassist.AbstractWsdlLanguageProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class WsdlLanguageProposalProvider extends AbstractWsdlLanguageProposalProvider {

}
