/*
 * generated by Xtext
 */
package nl.dslmeinte.multilevel.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ExampleDslUiModule extends nl.dslmeinte.multilevel.ui.AbstractExampleDslUiModule {
	public ExampleDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
