/*
* generated by Xtext
*/
package nl.dslmeinte.xtext.xsd.ui.contentassist;

import nl.dslmeinte.xtext.xsd.ui.contentassist.AbstractXsdLanguageProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class XsdLanguageProposalProvider extends AbstractXsdLanguageProposalProvider {

}
