/*
 * generated by Xtext
 */
package nl.dslmeinte.multilevel.ui.contentassist

import nl.dslmeinte.multilevel.ui.contentassist.AbstractExampleDslProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class ExampleDslProposalProvider extends AbstractExampleDslProposalProvider {
}
