/*
 * generated by Xtext
 */
package nl.dslmeinte.xtext.express.expression.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ExpressionUiModule extends nl.dslmeinte.xtext.express.expression.ui.AbstractExpressionUiModule {
	public ExpressionUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
