/*
 * generated by Xtext
 */
package nl.dslmeinte.xtext.dtd;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class DtdRuntimeModule extends nl.dslmeinte.xtext.dtd.AbstractDtdRuntimeModule {

}
