/*
 * generated by Xtext
 */
package nl.dslmeinte.xtext.conditional.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ConditionalUiModule extends nl.dslmeinte.xtext.conditional.ui.AbstractConditionalUiModule {
	public ConditionalUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
