/*
 * generated by Xtext
 */
package nl.dslmeinte.xtext.conditional;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ConditionalRuntimeModule extends nl.dslmeinte.xtext.conditional.AbstractConditionalRuntimeModule {

}
