/*
* generated by Xtext
*/
package nl.dslmeinte.xtext.dtd.ui.contentassist;

import nl.dslmeinte.xtext.dtd.ui.contentassist.AbstractDtdProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class DtdProposalProvider extends AbstractDtdProposalProvider {

}
