/*
 * generated by Xtext
 */
package nl.dslmeinte.xtext.examples;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class DataModelDslRuntimeModule extends nl.dslmeinte.xtext.examples.AbstractDataModelDslRuntimeModule {

}
