/*
* generated by Xtext
*/
package nl.dslmeinte.xtext.wsdl;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class WsdlLanguageUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return nl.dslmeinte.xtext.wsdl.ui.internal.WsdlLanguageActivator.getInstance().getInjector("nl.dslmeinte.xtext.wsdl.WsdlLanguage");
	}
	
}
