/*
* generated by Xtext
*/
package nl.dslmeinte.xtext.express.ui.contentassist;

import nl.dslmeinte.xtext.express.ui.contentassist.AbstractExpressProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class ExpressProposalProvider extends AbstractExpressProposalProvider {

}
