/*
* generated by Xtext
*/
package nl.dslmeinte.xtext.sgml.test.simplemarkup.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class SimpleMarkupOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
