/*
 * generated by Xtext
 */
package nl.dslmeinte.xtext.ambiguity;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MyPLRuntimeModule extends nl.dslmeinte.xtext.ambiguity.AbstractMyPLRuntimeModule {

}
