/*
* generated by Xtext
*/
package nl.dslmeinte.xtext.ambiguity;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class MyPLStandaloneSetup extends MyPLStandaloneSetupGenerated{

	public static void doSetup() {
		new MyPLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

