/*
 * generated by Xtext
 */
package nl.dslmeinte.xtext.express.expression;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ExpressionRuntimeModule extends nl.dslmeinte.xtext.express.expression.AbstractExpressionRuntimeModule {

}
