/*
 * generated by Xtext
 */
package nl.dslmeinte.xtext.ambiguity.ui.contentassist

import nl.dslmeinte.xtext.ambiguity.ui.contentassist.AbstractMyPLProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class MyPLProposalProvider extends AbstractMyPLProposalProvider {
}
