/*
* generated by Xtext
*/
package nl.dslmeinte.xtext.sgml.test.simplemarkup.ui.contentassist;

import nl.dslmeinte.xtext.sgml.test.simplemarkup.ui.contentassist.AbstractSimpleMarkupProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class SimpleMarkupProposalProvider extends AbstractSimpleMarkupProposalProvider {

}
